a='user name:'
b='The first name of the autistic :'
c='The last name of the autistic :'
d='The password :'
e='The name of the responsible :'
f='The E-mail of the responsible :'
g='The number phone of the responsible :'
h='your explain is :'
i="I accept the Terms of service "
j='Create'
k="Type message:"
l="send"
m="choose"
n='Language'
o="contact"
p="help!"
q='profile pic'
r='create new account'
s="category"
t="from computer"
u='name of image:'
v="Add voice  "
w="Add pic "
x=" save "
y="Enter"
z='board name:'
back='<-Back'
update='update'
eng='English'
heb='Hebrew'
arab='Arabic'

aa="Setting"
bb="Create a new board!"
cc="An existing boards"
dd='New Password'
ee='Enter new password:'
ff='Enter the password one more time:'
gg='change password'
hh='Account security'
ii='your id:'
jj='what your primry school?'
kk='OK'
ll='Enter username you want to search:'
mm=" Search"
nn="add a new board"
oo="all boards"
pp='catigoria name:'
qq="add a new catigoria"
rr="all catigorias"
ss="Enter user name:"
tt="Enter password:"
uu="Enter first name:"
vv="Enter last name:"
ww="add"
xx="Search an User"
yy="boards"
zz="Catigoria"
aaa="Update the page explain "
bbb="My design "
ccc="add admin "
ddd='enter your new explain'
eee="Ok"
fff="Happy Birthday ya qalbiy :) "
ggg="Delete an user"
hhh="Wish a Happy Birthday"
iii="Send A massage "
jjj='Enter your massage thats you want to send to user '
kkk="Send"
lll="Enter user name:"
mmm="Enter password:"
nnn='login'
ooo="forget password"
ppp="Choose Login Or Register"
qqq="Login"
rrr="Register"
mainpage='main page'
Home="Home"
logout="logout"
DeBo="Delete board"
ddd="Enter name the board ,you want to delete:"

tt='the Termos:\n • Not allowed > upload disturbing images\n •Not allowed to extract audio > that has unsuitable words.' \
'\n• The system should be used correctly.\n• Allow managers to control my account.\n• ' \
'Confirmation of saving my personal information in the system'